### PR TITLE
more item cmds

### PR DESCRIPTION
**Pull request by Marathxnz**

### CODE REVIEW

**Comment by vim2meta** [comment]
First off, I would appreciate if you didn't name your PR's with retarded shit.

**Comment by Marathxnz** [comment]
cry me a river

**Comment by vim2meta** [comment]
Edits needed:
- Create a `HealthService`
- Add `reduceDamage()`, have it take the id of the person attacked and the damage, inside this method, u fetch their armor, do the loop, and modify a **COPY** of the damage (don't modify the arg itself), then return this copy, example: `const damage = reduceDamage(args.member.id, args.knife.damage);`
- Only declare variables RIGHT before you use them. The `roll` const should be declared only right before the comparison itself. If one of those db queries were to fail, you would have another unused const in memory.
- All DMs to other users always have to be wrapped in `Try()` from `utility/` to prevent the command from being interrupted (and preventing the removal of bullets -> dupe). Example: `await Try(Sender.send(args.member, 'test'));`
- The `if/else` inside if `Food` is useless. Just simply create a variable called `increase`. Set the variable to the food health, and if `increase + dbUser.health > 100`, set that variable to the amount of health needed to reach 100, which is `100 - dbUser.health`, then pass that into `modifyHealth()`. 
- 3 times you use the variable name `newDbUser` when it is NOT a `dbUser` at all. The methods `modifyX` always return the modified result. For example. `modifyHealth()` returns the modified HEALTH, not the `dbUser` containing the health property. Fix all of those.
- Inside `OwnBullets`, there are 3 mistakes. The first one is you do 2 queries when you can do the exact same thing in one. Simply join with the `items` table directly. Second one is you do ` AND quantity >= 1` even though this will ALWAYS be true. The sole method that modifies the inventory checks interally if its under 1, and if it is the element is delete. The last one is you should sort the bullets by damage, so `ORDER BY b.damage DESC`, so that when shooting it will always take the best bullet. Also, you should assign the first row inside the precondition of this result to `msg.bullet` to avoid requerying the exact same thing inside the command.
- Change the response in `Eat` to `You ate one x increasing your health to 56.`

**Comment by vim2meta** [comment]
very nice work me boy, one day u will make big dream come true

**Pull request merged**
